### ISSUE TITLE
New Next Gen DLC "Blue Sun" this 14th

### ISSUE THREAD

**Issue by Teysara** [Synthlight/Hellpoint-Save-Editor#11]
we wait for your coming back to update the editor for upcoming DLC :)

**Comment by Synthlight** [comment]
I don't expect the save format to change, it'll most likely just be new IDs. Maybe it'll finally get me back into the game though and I can add the other IDs from the other issues.

**Comment by Teysara** [comment]
🙂 i'll wait fore next gen update they claim to be
❤️ so hype! saw some new cool weapons in the pics

________________________________
