### ISSUE TITLE
Can't figure out how to start this program

### ISSUE THREAD

**Issue by Keeper216** [Synthlight/Hellpoint-Save-Editor#3]
As the title. What file starts this?

**Comment by Synthlight** [comment]
It's literally an exe. One of the 5 files in the release.

**Comment by Keeper216** [comment]
I don't see any .exe file anywhere.
![image](https://user-images.githubusercontent.com/45796920/90826935-f188c900-e300-11ea-82a0-06e15564cca6.png

**Comment by Synthlight** [comment]
You have downloaded the source code, **not** the release.
The green "Clone" button **only** downloads source code. Go to the releases section.
