### ISSUE TITLE
Crash when trying to edit "alive" value of NPCs

### ISSUE THREAD

**Issue by grimux** [Synthlight/Hellpoint-Save-Editor#5]
Under the NPC tab, when trying to change the value for `alive` , the program crashes.  I can manually edit the save file and set the state to `true` to respawn a boss.  But having this work in the editor would be much more convenient.

Debug shows: `System.InvalidOperationException: ''EditItem' is not allowed for this view.'`

I don't really know C# 😅, but I will try to fix this.  If this is easy for you, feel free to go ahead and I will study your fix!

**Comment by Synthlight** [comment]
Turns out wpf/datagrid doesn't like editing a row when bound to a dictionary.
Committed/pushed a workaround. Also changed that field to a checkbox.

Let me know if you need me to create a release, if not I'll probably just leave it till you've mapped out more, or gave up from the hassle. :P

**Comment by grimux** [comment]
Okay cool!  I just built and tested it and it's working!  I started trying to implement a solution on my fork, I'm just trying to follow your code but I don't really know what I'm doing.  Maybe if you have time you could look.  I really like the checkbox though!

I will continue to add the bosses and will send a PR when I've got a chunk of them.  I'm really enjoying this game at the moment so I don't mind 😄

**Comment by Synthlight** [comment]
> I started trying to implement a solution on my fork, I'm just trying to follow your code but I don't really know what I'm doing. Maybe if you have time you could look.

What's the issue now? Edit should be fixed. Or if you mean adding the IDs, you already had it right in that PR. They're mostly just hard-coded like that. There's on ID dump file for items, but the localized stuff is all in Data.cs. Adding to it should be fairly straigh-forward.

**Comment by Synthlight** [comment]
I'm gonna close this issue as solved. If you need help with whatever you're doing, poke me on discord: `LordGregory#4687`
