### ISSUE TITLE
IDs from Event

### ISSUE THREAD

**Issue by DawnTroll** [Synthlight/Hellpoint-Save-Editor#6]
i'v been messing around with the save editor and by manually looking at the IDs of the Halloween event i made a list of all the gear and their IDs where would i send them ?
granted your still supporting this 
PS : sorry if this should be somewhere else first time posting

**Comment by Synthlight** [comment]
You can either post a list here, or edit the file yourself and make your own PR: https://github.com/Synthlight/Hellpoint-Save-Editor/blob/master/Data.cs

If you just put the list here, I'll update it in a day or so.

**Comment by DawnTroll** [comment]
[event IDs.zip](https://github.com/Synthlight/Hellpoint-Save-Editor/files/5599650/event.IDs.zip)
heres a ZIP and also raw text	

Devilish Set
				Helmet
9ef7fcc1-051e-409f-848c-e2bfb2c66c17
				Torso
a0c92a28-f4fc-425d-afcc-3ec720ad2c51
				Gloves
d1d2db6b-c1fe-49b4-829c-4312f29cd82b
				Legs
6addebb1-9967-4d92-aebe-49b64ece7561


			Toxic Set
				Helmet
5f7af854-1a5d-41df-a282-acfcd8ff1763
				Torso
24852a0d-452c-4d97-b88b-8961dcce8f2e
				Gloves
e3fda2e0-5448-4ded-b9d7-781c28ec5262
				Legs
861940b3-f490-4e91-9803-32e99a68e06b

			Preterhuman Lord
				Helmet
56417ea8-c15e-4d91-bf62-41c653c62f07
				Torso
0c030c7a-eaa9-4072-a224-66976165ed10
				Gloves
a5e02c3a-c5c2-4ad3-aca5-ad7868e096c1
				Legs
61536473-7a89-41df-b5c5-6a14f3044566

				Uniques
			Spaceship Omnicube
565f38f5-156a-400c-845e-d4ea4063a0af
				Alien Wear
afd4096d-0641-45a6-a888-b1e49119fd95
	Omnicube Jukebox Hallow's Eve
5b7a0cdd-0151-4869-ad06-e911278ac3ce
Omnicube Jukebox Debilitating Music
d8e0f942-aba0-4453-9e9e-43b290c6e9a3
				Witch Hat
465b351b-c382-4951-baaa-ab81f3266965
			Expression Mask
55c11a1c-5d67-4e67-b2e8-c5672c117f61
		Pumpkin Headdress
e2e15271-c1fb-407b-a9c0-8c99f87e6799
		Strange Sport Mask
8fedde13-792d-4f3b-906b-7cfb8a658e86
				Silly Eyes
abf77367-6a7b-4156-b083-214a02e8312f
			Transhuman Mask
b77fcb3e-4869-48ad-a3d2-2dd4607d0efe
			Carnival Mask
05be3ae6-36d1-4b96-9ede-f8ef2f1fe968
				Bone Bat
c01629d3-b114-49c1-8ed6-c616e64b7669
			Scary Scooper
fba5eeb8-666d-498b-90dc-59a2d940e996
			Coffin Crusher
afba624d-4ba5-441a-9943-a71a8734fc1a

	Nihl Bonbons (stackable)
a70ee5c4-7dc2-4ee3-87ee-5efdd138b4e3
(side note they seemed to have been removed after the event ended and adding them again has no visual effect)
*its also possible this ID is for something else and the Bonbons have a separate ID that was removed*

**Comment by Synthlight** [comment]
Ok, should be added by https://github.com/Synthlight/Hellpoint-Save-Editor/commit/efefe6d68174f9f65f0f4d243b6f9fb5f1109282
Feel free to double check the IDs.
I'll make a release build later today or tomorrow.

**Comment by Synthlight** [comment]
Released in https://github.com/Synthlight/Hellpoint-Save-Editor/releases/tag/v1.3.2
