### ISSUE TITLE
Arena update items

### ISSUE THREAD

**Issue by KittySkin** [Synthlight/Hellpoint-Save-Editor#8]
Here is the list of IDs for the new arena items. Courtesy of DawnTroll.

Argent Warrior Set:

Helm
a5ced55d-07b5-4a23-afd2-2ca6984d5a5b
Armor
69d5db8a-c449-418b-b6a7-5f81b2d0ed03
Gauntlets
929ad7d0-8eca-4a25-8124-b7e7e1bebeaa
Boots
b5fa30f4-6eb7-4d49-88ff-52e279c955cd

Crimson Sentinel Set:

Crown (helm)
25002700-8a36-4546-a804-dea78bd9c9ef
Armor
a696fdf8-4f7f-4487-8677-ca8bb26ceb13
Gauntlets
be9ecfc0-fc1c-4f31-b91b-9483f2f10623
Leggins
df4f65a2-1276-4daf-b4bc-3b951299ea5a

Nanocarbon Set:

Helm
ab1caa5d-9611-42b8-8d31-a7183cb0677f
Exosuit (armor)
6ef5a440-1121-431d-959a-356366967349
Gauntlets
cf96cc06-b466-460e-aa0b-524e2c763106
Leg Support (Boots)
fd0f90d7-c6d1-429a-9674-0b0bb5623d59
Pristine EVA Suit
Helmet
b29ddf02-bced-4780-a172-266a61f7f312
Chest
56731cd4-5e78-4da7-a003-107753961408
Gloves
1095019e-78da-489b-85ae-1d046333014a
Legs
12b223a3-ed64-48bd-a506-0f4f6ca46694

Aureate Warrior Set:

Helm
9110a5ec-d8d0-44d9-99fd-e521531b4ee4
Armor
b35ad384-300c-424a-aafd-67783563af69
Gauntlets
469f2755-750c-4452-9052-adccf74e8e15
Boots
c5e3e264-8545-4b98-a594-77c8e4a608f8

**Comment by Synthlight** [comment]
Nice. Thanks.

**Comment by Synthlight** [comment]
Added in https://github.com/Synthlight/Hellpoint-Save-Editor/releases/tag/v1.3.3
